movies = [
    {
        'id':0,
        'title':"Chinatown",
        "author":"William Goldman",
        "characters": [
            ("gittes", 536 ),
            ("evelyn", 184 ),
            ("escobar", 74 ),
            ("cross", 73 ),
            ("curly", 26 ),
            ("yelburton", 20 ),
            ("walsh", 19 ),
            ("secretary", 14 ),
            ("pilot", 13 ),
            ("mrs. mulwray", 12 ),
            ("morty", 11 ),
            ("palmer", 10 ),
            ("barney", 8 ),
            ("emma", 8 ),
            ("ida's voice", 7 ),
            ("clerk", 7 ),
            ("red faced farmer", 7 ),
            ("sophie", 8 ),
            ("duffy", 5 ),
            ("other customer", 5 ),
            ("young woman", 5 ),
            ("mulvihill", 5 ),
            ("the boy", 4 ),
            ("rainmaker", 4 ),
            ("voice on phone", 4 ),
            ("farmer", 3 ),
            ("gardener", 3 ),
            ("loach", 3 ),
            ("mrs. match", 3 ),
            ("big farmer", 3 ),
            ("dubois", 3 ),
            ("third assistant", 3 ),
            ("woman", 2 ),
            ("bagby", 2 ),
            ("gray-haired man", 2 ),
            ("chinese butler", 2 ),
            ("guard", 2 ),
            ("smaller man", 4 ),
            ("maid", 2 ),
            ("councilman", 1 ),
            ("mulwray", 1 ),
            ("council president", 1 ),
            ("a fireman", 1 ),
            ("woman's voice", 1 ),
            ("old man", 1 ),
            ("child", 1 ),
            ("crippled farmer", 1 ),
            ("dubois,", 1 ),
            ("palmer's voice", 1 ),
            ("voice on phone", 1 ),
            ("escobar's assistant", 1 ),
            ("one of assistants", 1 ),
            ("escobar", 1 ),
            ("chinese servant", 1 ),
            ("katherine", 1 ),
            ("wife", 1 ),
        ]
    },
    {
        'id':1,
        'title':"Her",
        "author":"Spike Jonze",
        "characters": [
            ("theodore", 421 ),
            ("samantha", 299 ),
            ("amy", 51 ),
            ("catherine", 21 ),
            ("paul", 20 ),
            ("blind date", 19 ),
            ("text voice", 17 ),
            ("sexykitten", 16 ),
            ("jocelyn", 14 ),
            ("alien child", 13 ),
            ("charles", 10 ),
            ("tatiana", 6 ),
            ("alan watts", 6 ),
            ("female os voice", 4 ),
            ("isabella", 4 ),
            ("letter writer 2", 2 ),
            ("soulful older male voice", 2 ),
            ("waitress", 2 ),
            ("middle-aged woman letter writer", 1 ),
            ("letter writer 3", 1 ),
            ("receptionist", 1 ),
            ("female voice #1", 1 ),
            ("man doing woman’s voice", 1 ),
            ("nice lady", 1 ),
            ("pizza vendor", 1 ),
        ]
    },
    {
        'id':2,
        'title':"The Lord of the Rings: The Fellowship of the Ring",
        "author":"Fran Walsh & Philippa Boyens & Peter Jackson",
        "characters": [
            ("gandalf", 174 ),
            ("frodo", 156 ),
            ("bilbo", 88 ),
            ("sam", 78 ),
            ("galadriel", 68 ),
            ("boromir", 62 ),
            ("aragorn", 58 ),
            ("merry", 46 ),
            ("strider", 39 ),
            ("pippin", 38 ),
            ("elrond", 37 ),
            ("gimli", 33 ),
            ("saruman", 31 ),
            ("legolas", 25 ),
            ("arwen", 22 ),
            ("haldir", 10 ),
            ("celeborn", 8 ),
            ("gollum", 5 ),
            ("butterbur", 5 ),
            ("old harry", 4 ),
            ("lobelia", 3 ),
            ("farmer maggot", 2 ),
            ("ted sandyman", 2 ),
            ("gaffer", 2 ),
            ("sauron", 2 ),
            ("orc overseer", 2 ),
            ("lurtz", 2 ),
            ("proudfoot", 1 ),
            ("black rider", 1 ),
            ("hobbits", 1 ),
            ("daddy twofoot", 1 ),
            ("rosie", 1 ),
            ("intoxicated hobbit", 1 ),
            ("hobbit bounder", 1 ),
            ("elven voices", 1 ),
            ("voice of sauron", 1 ),
            ("witch king", 1 ),
            ("isildur", 1 ),
            ("the ring", 1 ),
            ("merry & pippin", 1 ),
        ]
    },
    {
        'id':3,
        'title':"Moonlight",
        "author":"Barry Jenkins",
        "characters": [
            ("kevin", 145 ),
            ("black", 75 ),
            ("juan", 65 ),
            ("paula", 55 ),
            ("chiron", 50 ),
            ("terrell", 38 ),
            ("teresa", 24 ),
            ("little", 21 ),
            ("voice", 11 ),
            ("travis", 9 ),
            ("mr. pierce", 8 ),
            ("pizzo", 7 ),
            ("portable boy 1", 6 ),
            ("terrence", 4 ),
            ("williams", 4 ),
            ("principal williams", 3 ),
            ("azu", 2 ),
            ("portable boy 3", 2 ),
            ("boy 2", 2 ),
            ("little boy 1", 1 ),
            ("kid", 1 ),
            ("portable boy 2", 1 ),
            ("boy 1", 1 ),
            ("old school guard", 1 ),
            ("automated voice", 1 ),
        ]
    },
    {
        'id':4,
        'title':"Knives Out",
        "author":"Rian Johnson",
        "characters": [
            ("blanc", 186 ),
            ("marta", 178 ),
            ("lieutenant elliott", 90 ),
            ("ransom", 61 ),
            ("harlan", 59 ),
            ("walt", 48 ),
            ("richard", 42 ),
            ("joni", 38 ),
            ("linda", 35 ),
            ("meg", 27 ),
            ("trooper wagner", 17 ),
            ("alan", 16 ),
            ("fran", 14 ),
            ("greatnana", 5 ),
            ("mr proofroc", 5 ),
            ("jacob", 5 ),
            ("mom", 4 ),
            ("alice", 4 ),
            ("donna", 4 ),
            ("sally", 3 ),
            ("cop", 2 ),
            ("elliott", 1 ),
            ("local news anchor", 1 ),
            ("phone", 1 ),
            ("wagner", 1 ),
        ]
    },
    {
        'id':5,
        'title':"Community - Pilot",
        "author":"Dan Harmon",
        "characters": [
            ("jeff", 117 ),
            ("britta", 42 ),
            ("duncan", 33 ),
            ("abed", 23 ),
            ("pierce", 17 ),
            ("troy", 11 ),
            ("annie", 11 ),
            ("pelton", 8 ),
            ("shirley", 8 ),
            ("old black woman", 5 ),
            ("coach bartel", 3 ),
            ("elderly black woman", 2 ),
            ("busta rhymes", 1 ),
        ]
    },
    {
        'id':6,
        'title':"Breaking Bad - Pilot",
        "author":"Vince Gilligan",
        "characters": [
            ("walt", 102 ),
            ("dupree", 50 ),
            ("skyler", 43 ),
            ("hank", 27 ),
            ("marie", 12 ),
            ("walter, jr.", 11 ),
            ("krazy-8", 11 ),
            ("margaret", 9 ),
            ("jock", 7 ),
            ("emilio", 5 ),
            ("amir", 3 ),
            ("doctor", 3 ),
            ("gomez", 3 ),
            ("branch manager", 3 ),
            ("dr. belknap", 2 ),
            ("agent", 2 ),
            ("underpants man", 1 ),
            ("student", 1 ),
            ("chad", 1 ),
            ("girlfriend", 1 ),
            ("tony montana", 1 ),
            ("teller", 1 ),
        ]
    },
]